### ISSUE TITLE
Kernel not connected

### ISSUE THREAD

**Issue by lordoftheflies** [lordoftheflies/muadib-notebook#2]
```python

[I 22:08:55.779 NotebookApp] Adapting to protocol v5.1 for kernel 971c484a-00a1-4529-a4fe-039d977a8c0e
[E 22:08:55.782 NotebookApp] Uncaught exception in /api/kernels/971c484a-00a1-4529-a4fe-039d977a8c0e/channels
    Traceback (most recent call last):
      File "/home/lordoftheflies/Documents/cherubits/muadib-notebook/env/lib/python3.5/site-packages/tornado/websocket.py", line 498, in _run_callback
        result = callback(*args, **kwargs)
      File "/home/lordoftheflies/Documents/cherubits/muadib-notebook/env/lib/python3.5/site-packages/notebook/services/kernels/handlers.py", line 260, in open
        super(ZMQChannelsHandler, self).open()
      File "/home/lordoftheflies/Documents/cherubits/muadib-notebook/env/lib/python3.5/site-packages/notebook/base/zmqhandlers.py", line 176, in open
        self.send_ping, self.ping_interval, io_loop=loop,
    TypeError: __init__() got an unexpected keyword argument 'io_loop'


```

**Comment by lordoftheflies** [comment]
Based on [this](https://github.com/jupyter/help/issues/272)

Tornado version needs to be: 4.5.3
